// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateRepositoryHandlerFunc turns a function with the right signature into a update repository handler
type UpdateRepositoryHandlerFunc func(UpdateRepositoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateRepositoryHandlerFunc) Handle(params UpdateRepositoryParams) middleware.Responder {
	return fn(params)
}

// UpdateRepositoryHandler interface for that can handle valid update repository params
type UpdateRepositoryHandler interface {
	Handle(UpdateRepositoryParams) middleware.Responder
}

// NewUpdateRepository creates a new http.Handler for the update repository operation
func NewUpdateRepository(ctx *middleware.Context, handler UpdateRepositoryHandler) *UpdateRepository {
	return &UpdateRepository{Context: ctx, Handler: handler}
}

/*UpdateRepository swagger:route PUT /projects/{project_name}/repositories/{repository_name} repository updateRepository

Update repository

Update the repository specified by name

*/
type UpdateRepository struct {
	Context *middleware.Context
	Handler UpdateRepositoryHandler
}

func (o *UpdateRepository) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateRepositoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
