# coding: utf-8

"""
    Harbor API
    These APIs provide services for manipulating Harbor project.
    OpenAPI spec version: 1.4.0
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import
import os
import sys
sys.path.append(os.environ["SWAGGER_CLIENT_PATH"])


import unittest
import testutils

from swagger_client.models.configurations import Configurations 
from pprint import pprint

# Test search LDAP user

class TestLdapUserSearch(unittest.TestCase):
    """UserGroup unit test stubs"""
    product_api = testutils.GetProductApi("admin", "Harbor12345")
    groupId = 0
    def setUp(self):

    def tearDown(self):
        pass

    def testSearchLdapUser(self):
        result = self.product_api.ldap_users_search_get(username="mike")
        pprint(result)
        self.assertTrue(len(result)>=1)
        pass

    def testSearchLdapUserNotExist(self):
        result =  self.product_api.ldap_users_search_get(username="not_found_user")
        pprint(result)
        self.assertTrue(result==None)

if __name__ == '__main__':
    unittest.main()
