// Code generated by go-swagger; DO NOT EDIT.

package artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CopyArtifactHandlerFunc turns a function with the right signature into a copy artifact handler
type CopyArtifactHandlerFunc func(CopyArtifactParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CopyArtifactHandlerFunc) Handle(params CopyArtifactParams) middleware.Responder {
	return fn(params)
}

// CopyArtifactHandler interface for that can handle valid copy artifact params
type CopyArtifactHandler interface {
	Handle(CopyArtifactParams) middleware.Responder
}

// NewCopyArtifact creates a new http.Handler for the copy artifact operation
func NewCopyArtifact(ctx *middleware.Context, handler CopyArtifactHandler) *CopyArtifact {
	return &CopyArtifact{Context: ctx, Handler: handler}
}

/*CopyArtifact swagger:route POST /projects/{project_name}/repositories/{repository_name}/artifacts artifact copyArtifact

Copy artifact

Copy the artifact specified in the "from" parameter to the repository.

*/
type CopyArtifact struct {
	Context *middleware.Context
	Handler CopyArtifactHandler
}

func (o *CopyArtifact) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCopyArtifactParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
