// Code generated by go-swagger; DO NOT EDIT.

package artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetArtifactHandlerFunc turns a function with the right signature into a get artifact handler
type GetArtifactHandlerFunc func(GetArtifactParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetArtifactHandlerFunc) Handle(params GetArtifactParams) middleware.Responder {
	return fn(params)
}

// GetArtifactHandler interface for that can handle valid get artifact params
type GetArtifactHandler interface {
	Handle(GetArtifactParams) middleware.Responder
}

// NewGetArtifact creates a new http.Handler for the get artifact operation
func NewGetArtifact(ctx *middleware.Context, handler GetArtifactHandler) *GetArtifact {
	return &GetArtifact{Context: ctx, Handler: handler}
}

/*GetArtifact swagger:route GET /projects/{project_name}/repositories/{repository_name}/artifacts/{reference} artifact getArtifact

Get the specific artifact

Get the artifact specified by the reference under the project and repository. The reference can be digest or tag.

*/
type GetArtifact struct {
	Context *middleware.Context
	Handler GetArtifactHandler
}

func (o *GetArtifact) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetArtifactParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
