// Code generated by go-swagger; DO NOT EDIT.

package artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAdditionHandlerFunc turns a function with the right signature into a get addition handler
type GetAdditionHandlerFunc func(GetAdditionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAdditionHandlerFunc) Handle(params GetAdditionParams) middleware.Responder {
	return fn(params)
}

// GetAdditionHandler interface for that can handle valid get addition params
type GetAdditionHandler interface {
	Handle(GetAdditionParams) middleware.Responder
}

// NewGetAddition creates a new http.Handler for the get addition operation
func NewGetAddition(ctx *middleware.Context, handler GetAdditionHandler) *GetAddition {
	return &GetAddition{Context: ctx, Handler: handler}
}

/*GetAddition swagger:route GET /projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/{addition} artifact getAddition

Get the addition of the specific artifact

Get the addition of the artifact specified by the reference under the project and repository.

*/
type GetAddition struct {
	Context *middleware.Context
	Handler GetAdditionHandler
}

func (o *GetAddition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAdditionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
