// Code generated by go-swagger; DO NOT EDIT.

package artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// RemoveLabelURL generates an URL for the remove label operation
type RemoveLabelURL struct {
	LabelID        int64
	ProjectName    string
	Reference      string
	RepositoryName string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RemoveLabelURL) WithBasePath(bp string) *RemoveLabelURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RemoveLabelURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *RemoveLabelURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/labels/{label_id}"

	labelID := swag.FormatInt64(o.LabelID)
	if labelID != "" {
		_path = strings.Replace(_path, "{label_id}", labelID, -1)
	} else {
		return nil, errors.New("labelId is required on RemoveLabelURL")
	}

	projectName := o.ProjectName
	if projectName != "" {
		_path = strings.Replace(_path, "{project_name}", projectName, -1)
	} else {
		return nil, errors.New("projectName is required on RemoveLabelURL")
	}

	reference := o.Reference
	if reference != "" {
		_path = strings.Replace(_path, "{reference}", reference, -1)
	} else {
		return nil, errors.New("reference is required on RemoveLabelURL")
	}

	repositoryName := o.RepositoryName
	if repositoryName != "" {
		_path = strings.Replace(_path, "{repository_name}", repositoryName, -1)
	} else {
		return nil, errors.New("repositoryName is required on RemoveLabelURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v2.0"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *RemoveLabelURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *RemoveLabelURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *RemoveLabelURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on RemoveLabelURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on RemoveLabelURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *RemoveLabelURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
