// Code generated by go-swagger; DO NOT EDIT.

package auditlog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListAuditLogsHandlerFunc turns a function with the right signature into a list audit logs handler
type ListAuditLogsHandlerFunc func(ListAuditLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAuditLogsHandlerFunc) Handle(params ListAuditLogsParams) middleware.Responder {
	return fn(params)
}

// ListAuditLogsHandler interface for that can handle valid list audit logs params
type ListAuditLogsHandler interface {
	Handle(ListAuditLogsParams) middleware.Responder
}

// NewListAuditLogs creates a new http.Handler for the list audit logs operation
func NewListAuditLogs(ctx *middleware.Context, handler ListAuditLogsHandler) *ListAuditLogs {
	return &ListAuditLogs{Context: ctx, Handler: handler}
}

/*ListAuditLogs swagger:route GET /audit-logs auditlog listAuditLogs

Get recent logs of the projects which the user is a member of

This endpoint let user see the recent operation logs of the projects which he is member of


*/
type ListAuditLogs struct {
	Context *middleware.Context
	Handler ListAuditLogsHandler
}

func (o *ListAuditLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAuditLogsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
